fix: 500, double exception when flask-restx expects dict from error handlers
Traceback looks like:

```
...
During handling of the above exception, another exception occurred:
...
AttributeError: 'Response' object has no attribute 'get'
...
```